### ISSUE TITLE
Searching with an absolute path

### ISSUE THREAD

**Issue by keithpitt** [bmatcuk/doublestar#1]
Hey there! I tried to do a glob searching using `/Users/keithpitt/Desktop/*.doc` but it didn't pick up any files. I checked out the source and thought it would be because the empty string here: https://github.com/bmatcuk/doublestar/blob/master/doublestar.go#L161 should be `"/"`. I hacked it in to test, and it still didn't work. Perhaps that type of search isn't supported? Thanks for you help!

**Comment by bmatcuk** [comment]
Hey @keithpitt! Thanks for the bug report... turns out you were on the right track. I've changed the empty string to `string(filepath.Separator)` to support our unfortunate Windows using friends. Your fix was correct, but if you were using `doublestar_test.go` to test, it wouldn't have worked because the test suite prepends `test/` to the paths to make them relative, and `test/Users/keithpitt/Desktop/*.doc` would have returned nothing.

Anyway, I've just commit the fix =)

**Comment by keithpitt** [comment]
Awesome, thanks for the speedy fix!

**Comment by bmatcuk** [comment]
No problem!
