### ISSUE TITLE
Return a File interface type instead of *os.File in OS interface Open method

### ISSUE THREAD

**Issue by c4milo** [bmatcuk/doublestar#42]
This makes easier to use doublestar when the calling code is already using a filesystem interface like go-billy or afero. I have a  fork with the changes here: https://github.com/c4milo/doublestar/commit/af79f844d63ce55bee1ca6b8d04ac96dc8fa38b5 

If there is interest, I can send a PR. 

Thanks 🙇

**Comment by bmatcuk** [comment]
Hi @c4milo, that sounds like a good idea to me! Unfortunately, I think it's a breaking change to doublestar's API, so, we'll probably need to cut a v2. Kinda sad, since it's such a small change, but I'd hate for people to wake up some morning and find their code isn't compiling. Do you agree? Or can you think of some way the change could be made in a backward compatible way?

**Comment by c4milo** [comment]
@bmatcuk, indeed, it wouldn't be backward compatible and will require cutting a major version. A less clean alternative is extending the OS interface with another `Open` method, maybe `Open2` 🤷 ,  that returns the file interface instead of the concrete `os` implementation. Then in https://github.com/bmatcuk/doublestar/blob/master/doublestar.go#L433 , running `vos.Open2()` if `vos.Open()` fails 😬

**Comment by bmatcuk** [comment]
Alrighty, I've copied over your changes and released a v2 =) Could you update your dependency to my v2 release just to make sure everything still works? Thanks!

**Comment by c4milo** [comment]
Works perfectly @bmatcuk, thank you!
