### ISSUE TITLE
The command "go get github.com/bmatcuk/doublestar/v2" does not work

### ISSUE THREAD

**Issue by pjsg** [bmatcuk/doublestar#52]
I'm trying to install v2 of doublestar according to the instructions in the [v2 readme](https://github.com/bmatcuk/doublestar/tree/v2), and I get:

$ go get github.com/bmatcuk/doublestar/v2
cannot find package "github.com/bmatcuk/doublestar/v2" in any of:
	/snap/go/6745/src/github.com/bmatcuk/doublestar/v2 (from $GOROOT)
	/home/me/gocode/src/github.com/bmatcuk/doublestar/v2 (from $GOPATH)

I'm running ubuntu 20.04 if that makes any difference.....

**Comment by bmatcuk** [comment]
Honestly, I haven't done a ton of go dev since they introduced modules - it seems pretty hacky. I believe you can get `go get` to download v2+ if you set the `GO111MODULE` environment variable to `on`, such as:

```bash
env GO111MODULE=on go get github.com/bmatcuk/doublestar/v2
```

Alternatively, if you create a `go.mod` file, it will automatically enable "module" mode and should do the right thing.

**Comment by pjsg** [comment]
Actually, when I first tried this, it was being fetched due to a go.mod file (https://github.com/gphotosuploader/gphotos-uploader-cli/blob/master/go.mod) and that failed. I then tied fetching it from the command line.....

I'm a go newbie, so if stuff doesn't work, I'm rather at a loss....
