### ISSUE TITLE
 Does not match when **/ and {} are combined

### ISSUE THREAD

**Issue by makiuchi-d** [bmatcuk/doublestar#63]
if `**/` is followed by `{...}`, `Match()` does not work correctly in v4.
it works fine until v3.

https://go.dev/play/p/chnmf65L8EK

**Comment by bmatcuk** [comment]
Thanks for the bug report, @makiuchi-d. Actually turns out there's a second, related bug with patterns such as `a*{b,c}` (one or more characters followed by a star and then a list of `{alts}`). Additionally, patterns of the form you discovered (`**/{a,b}`) do not produce correct results with Glob/GlobWalk - specifically, they do not return paths for which `**` is replaced with nothing such as `a` or `b` in my example (but they do correctly match nested paths such as `nested/a` or `deeply/nested/b`, etc).

I know what the issues are for all three bugs. I've got a fix for the Glob/GlobWalk problem (was only half a line of code) and I'm trying to figure out what the best way would be to solve the other two. Hopefully have something later this weekend. Covid has been kicking my ass 😢

**Comment by bmatcuk** [comment]
I fixed all three bugs and released v4.0.3 just now. Let me know if you discover any more issues!

**Comment by makiuchi-d** [comment]
Thank you for the fix.
It now works perfectly.

Please take care of yourself.
