### ISSUE TITLE
doublestar at end of string doesn't match empty string

### ISSUE THREAD

**Issue by johnSchnake** [bmatcuk/doublestar#7]
I would have expected
```
abc**
```
to match
```
abc
```
but it does not. If `**` matches _one or more_ occurrences of any character then this is incompatible with the fact that `**abc` matches `abcc` just fine.

**Comment by bmatcuk** [comment]
Sorry for the slow reply; I've been out of town. This sounds like a bug to me. I'll look into it.

**Comment by bmatcuk** [comment]
I've corrected the issue, but, upon thinking about it some more, what is the expected behavior when using a doublestar with other characters? All of the examples I could find from other languages (say, bash, for example) with doublestar/globstar support only show it being using like `path/**/file`... what would `path/abc**/file` do? With this fix, the behavior is that the `**` is actually just treated like a single `*` so `path/abc**/file` would match `path/abc/file` and also `path/abcd/file`, etc, but doesn't match any nested paths.

But I was thinking: should `path/abc**/file` match something like `path/abcd/abcd/abcd/file` (ie, `abc**` expands recursively as `abc*`)? Or, should `path/abc**/file` be treated like `path/abc*/**/file`? The latter might make more sense, but I think the behavior is undefined. Thoughts?
