### ISSUE TITLE
`Glob` incorrectly returns errors if pattern does not match when failing on IO errors

### ISSUE THREAD

**Issue by twpayne** [bmatcuk/doublestar#73]
This code:

```go
matches, err := doublestar.Glob(fsys, "non-existent-path", doublestar.WithFailOnIOErrors())
```

incorrectly returns an error if `non-existent-path` does not exist. It should return an empty list of matches and no error.

The [`exists` function](https://github.com/bmatcuk/doublestar/blob/master/glob.go#L338-L342) is certainly buggy, as it returns an error when a file does not exist, whereas it should return `false` and no error. It should be something like:

```go
// Returns true if the path exists
func (g *glob) exists(fsys fs.FS, name string) (bool, error) {
	_, err := fs.Stat(fsys, name)
	if errors.Is(err, fs.ErrNotExist) { // name not existing is not an error
		return false, nil
	}
	return err == nil, g.forwardErrIfFailOnIOErrors(err)
}
```

**Comment by fho** [comment]
This is the expected behavior, see also https://github.com/bmatcuk/doublestar/pull/71#issuecomment-1298881798

**Comment by twpayne** [comment]
I'd argue that this behavior is incorrect. Consider the current behavior:

| Pattern | Directory contents | Result of `Glob` |
| - | - | - |
| `*.txt` | `a.txt` | `[]string{"a.txt"}` |
| `*.txt` | empty | `nil` |
| `a.txt` | `a.txt` | `[]string{"a.txt"}` |
| `a.txt` | empty | error |

Why should the user removing `a.txt` cause `Glob` to return an error instead of returning no matches?

**Comment by bmatcuk** [comment]
Hmm, this is a tough call because I could see arguments both ways. I've typed dozens of replies to this github issue and keep backtracking because my opinion keeps changing...

I guess one question that comes to mind is: if you do _not_ consider this an error, what IO errors _are_ you concerned with? Why not just run doublestar without the `WithFailOnIOErrors` option?

This is a bit of a corner case because I believe the only time doublestar would return `ErrNotExist` is if the pattern, itself, contains path components that don't exist. All other Stat's in doublestar are the result of getting a path while walking the filesystem, so, theoretically, those should never return ErrNotExist... unless it's deleted between reading the directory and Stat'ing it 🤷 

Part of me wants to say that the desired result should be an empty list without an error since the pattern doesn't match anything - and I agree that this would be the more consistent and expected behavior. But, the other part of me wants to say it's _definitely_ an IO error, and you asked for IO errors when you passed `WithFailOnIOErrors`. I could see how it might be useful to get this error so that you can tell the user that their pattern references a path that doesn't exist. It might indicate that the user made a mistake, as opposed to other IO errors which indicate things like permission issues or filesystem issues. Having the ability to distinguish between those errors is useful.

But that also means that if you _are_ concerned about IO errors, but you are _not_ concerned with this specific error, you could use `WithFailOnIOErrors` and check `fs.ErrNotExist` yourself after running Glob - if the error is ErrNotExist, throw it away and act as if doublestar returned nothing. That's essentially all doublestar would be doing if I changed the behavior. Difference being: if you handle it on your end, doublestar can continue to report the error, which someone else might find useful. If I change doublestar, then that makes doublestar slightly less flexible for other use-cases. For this reason, I'd lean toward keeping the behavior as-is.

I could update the documentation to make this clear. Would that be sufficient @twpayne? Or would you still prefer some sort of change in doublestar?

**Comment by twpayne** [comment]
> I guess one question that comes to mind is: if you do _not_ consider this an error, what IO errors _are_ you concerned with? Why not just run doublestar without the `WithFailOnIOErrors` option?

This is a bit of a misleading question, as a file not existing is not an I/O error.

Example errors I would like to be surfaced include, say, permission errors (e.g. when a user does not have permission to read a subdirectory), and errors that indicate that the filesystem changed while being iterated over. I would also expect to get an error if the underlying filesystem is corrupt, e.g. if any syscall returns `EIO`. As a general rule, I do not think silently ignoring errors and returning partial (i.e. incomplete) results is good practice. **However** I realize that the standard library's `io/fs.Glob` function behaves this way, so I'll accept it for now.

> I could update the documentation to make this clear. Would that be sufficient @twpayne? Or would you still prefer some sort of change in doublestar?

Fundamentally, I want a function that given a file system and a pattern, returns a list of entries in that file system whose names match that pattern.

The issue I've raised here is that `doublestar.Glob`'s current behavior is inconsistent and inconsistent in a way that makes the function particularly hard to use. `doublestar.Glob` should return a list of files that match a given pattern. That list should be empty if no files match the pattern. A file not existing is not an I/O error. A non-existent file cannot match a pattern.

With the current behavior, `doublestar.Glob` returns an error if the pattern matches exactly one file that doesn't exist, and no error if the pattern can match more than one file (and by extension, matches an unlimited numbers of files that don't exist).

> you could use `WithFailOnIOErrors` and check `fs.ErrNotExist` yourself after running Glob - if the error is ErrNotExist, throw it away and act as if doublestar returned nothing.

`fs.ErrNotExist` is only returned if the pattern can only match one file and that file doesn't exist. This means that whether the returned `fs.ErrNotExist` error can be thrown away or not depends on me having to analyze the pattern and determine whether it indeed can only match one file (in which case the error can be thrown away) or if the pattern can match more than one file (in which case the error is genuine and should not be ignored). `doublestar` currently does not provide a function to say if a pattern can only match a single file.

So, a documentation change is not sufficient. `doublestar.Glob`'s behavior needs to change to be consistent, i.e. where the behavior is the same irrespective of how many entries the pattern can match.

**Comment by twpayne** [comment]
As an additional comment, in my case the pattern is specified by the user and the file system is controlled by the user. I want to be able to write a single piece of code that handles all combinations of pattern and file system correctly, and specifically not have to write a special case for when the user-specified pattern can only match one entry in the user-controlled file system and that entry doesn't exist.

**Comment by fho** [comment]
I agree now with @twpayne that the inconsistency is bad and confusing.
The interpretation of the passed `pattern` parameter changes when the `WithFailOnIOErrors` option is passed. Without `WithFailOnIOErrors` the parameter is always a pattern. With `WithFailOnIOErrors` the parameter is interpreted as pattern and sometimes as path that must exist.

I suggest to change the behavior when using `WithFailOnIOErrors` to consistently return an empty list if a pattern does not match anything, instead of `fs.ErrNotExist` sometimes.

To still support to have a `fs.ErrNotExist` error when a pattern is passed that is a filepath and it does not exist, the following solutions come to my mind:
1. Introduce another Option that enables returning an `fs.ErrNotExist` error if a pattern is a path and it does not exist.
2. Alternatively doublestar could export a `IsGlobPattern(p string) bool` function. When `IsGlobPattern(p)`, returns false, the user could only check if the path exist and then eventually return `fs.ErrNotExist`.
If `IsGlobPattern()` returns true, he can call `Glob()` and handle an empty result as wanted.


Option 1. should have a better performance.
Option 2. is more generic, there might also be other usecases for an `IsGlobPattern()` function. It also seems more elegant to me.

**Comment by bmatcuk** [comment]
To be clear, my reply above was a rambling stream-of-consciousness, not meant as argumentative... just trying to think through the problem and the ramifications for a broader user-base. I think both sides are equally valid. But it seems we agree that the current behavior is inconsistent, so I'm happy to fix it.

Can either of you think of any situations where ErrNotExist _should_ be returned? I want to ensure that the fix is not overly broad. The only thing I can think of is if a file or directory is deleted/moved after the parent directory is read, but before doublestar traverses it.

**Comment by fho** [comment]
I'm unsure how broken symlinks should be handled.
doublestar is following directory symlinks. I would classify broken symlinks as I/O errors, therefore returning `fs.ErrNotExist` makes sense.
**But** when doublestar is encountering a symlink targeting a file, it is returning the path of the symlink, not the resolved path.
Because the unresolved paths are returned, returning `fs.ErrNotExist` seems inconsistent.
It's not possible to determine if a broken symlink would have pointed to a file or directory though.

@bmatcuk let me know if you prefer that I create a fix for the issue that I introduced :-)

**Comment by bmatcuk** [comment]
No worries, it's a fairly easy fix... I can handle it =)

**Comment by fho** [comment]
@bmatcuk thanks! :-)
What do you think about the alternative options that I suggested in https://github.com/bmatcuk/doublestar/issues/73#issuecomment-1299887740 regarding still supporting having detailed errors when a pattern is a path and does not exist

**Comment by bmatcuk** [comment]
I was thinking of adding an option that would thrown an error, but only if someone actually requested it. Do you think it'd be a useful feature? Should I go ahead and add it now?

**Comment by fho** [comment]
@bmatcuk to throw `fs.ErrNotExist` if a pattern is a path and it does not exist? 
Yes, I think that is useful.

**Comment by bmatcuk** [comment]
The solution was actually a bit more involved. I've [opened a PR](https://github.com/bmatcuk/doublestar/pull/74) and I'd appreciate if you both gave it a quick test to make sure it works the way you expect before I merge it.

One caveat is that, because of poor symlink support in io.fs, I cannot differentiate broken symlinks from other nonexistent paths. In other words, I must treat a pattern such as `nonexistent/*` the same as `broken-symlink/*`, so, for that reason, broken symlinks won't return an IO errors. We can revisit that if [this golang proposal](https://github.com/golang/go/issues/49580) is ever implemented. Not sure if either of you expected broken symlinks to return an error or not, but I wanted to mention it.

**Comment by fho** [comment]
@bmatcuk I did a few manual tests and looks good, behaves as I would expect with `doublestar.WithFailOnIOErrors()`.

I'm now of course missing the ability to get an fs.ErrNotExist if the whole or a part of the pattern is a filepath and it does not exist.

**Comment by bmatcuk** [comment]
Ya, I'm going to add that as a separate feature... I don't want to overload this PR with too much.

@twpayne do you have any input on my PR?

**Comment by bmatcuk** [comment]
v4.3.1 released with this bug fixed. I also addressed the small issue @twpayne found in the PR and added some tests that cause IO errors to flex that code 😄

**Comment by bmatcuk** [comment]
@fho here's a PR to add at option to fail if the pattern doesn't exist: https://github.com/bmatcuk/doublestar/pull/75

**Comment by twpayne** [comment]
Thank you for the speedy fix :)

**Comment by bmatcuk** [comment]
You're welcome =)
