### ISSUE TITLE
PathMatch in v4 no longer working in Windows

### ISSUE THREAD

**Issue by darnvisages** [bmatcuk/doublestar#77]
From doublestar v3 to doublestar v4, it appears that the matching in `PathMatch()` has changed. 

The same pattern/path pair returns `true` in v3 and returns `false` in v4.

A test that demonstrates the behavior:
```
package doublestar_windows_bug

import (
	"testing"

	doublestarv3 "github.com/bmatcuk/doublestar/v3"
	doublestarv4 "github.com/bmatcuk/doublestar/v4"
	"github.com/stretchr/testify/assert"
)

func TestDoublestarWindows(t *testing.T) {
	pattern := "foo/**/*.md"
	path := "foo\\test\\bar\\baz\\1.md"

	match, _ := doublestarv3.PathMatch(pattern, path)
	assert.True(t, match)

	match, _ = doublestarv4.PathMatch(pattern, path)
	assert.False(t, match)
}
```

I was able to replicate the doublestar v4 `PathMatch()` behavior in Windows versions 21H2, 22H2 and 1809, but I'm unsure of how many versions are affected in total.

The above test was confirmed on a machine with the following:
Edition:	`Windows 10 Home`
Version:	`22H2`
OS build:	`19045.2251`
Experience:	`Windows Feature Experience Pack 120.2212.4180.0`

Note: due to the `\\` path separators, the above test will fail in MacOS / Linux.

**Comment by darnvisages** [comment]
I did a read through on the docs and it looks like the issue is that the example path/pattern pair that I provided is using different separators, `\\` and `/`, and `PathMatch()` assumes they will both use the system's path separator.  v3 seemingly didn't make this same assumption?

Is there any plan to make v4 capable of matching with a pattern and path that use different separators?

**Comment by bmatcuk** [comment]
I would consider v4 behavior to be correct and this to be a bug in v3: PathMatch uses the OS path separator as described in the documentation. There are a couple ways you could get this to work, though, using `filepath.ToSlash` and `filepath.FromSlash`. For example, you could pass both pattern and path through `ToSlash` and then use `doublestar.Match` instead:

```go
pattern = filepath.ToSlash(pattern)
path = filepath.ToSlash(path)
doublestar.Match(pattern, path)
```

If you prefer to use `PathMatch`, you could pass both pattern and path through `FromSlash`:

```go
pattern = filepath.FromSlash(pattern)
path = filepath.FromSlash(path)
doublestar.PathMatch(pattern, path)
```

And, of course, if you know that either pattern and/or path is already using the right slashes, there's no reason to call ToSlash/FromSlash. In your example, you already know path has the OS separators, so you could do either of these:

```go
// using PathMatch:
pattern = filepath.FromSlash(pattern)
doublestar.PathMatch(pattern, path)

// using Match:
path = filepath.ToSlash(path)
doublestar.Match(pattern, path)
```

Which you use is up to you. However, if you suspect that the pattern may use some escape sequences (ie, the backslash is used to escape characters that otherwise have meaning in glob), then you're probably best off using `path = filepath.ToSlash(path)` and `doublestar.Match` because backslashes are treated as path separators in PathMatch on Windows.

**Comment by darnvisages** [comment]
@bmatcuk Thanks so much for the thorough and helpful reply! Your suggestion did the trick. 

I also realized I needed to update a `path` with `path = filepath.ToSlash(path)` for the v4 `doublestar.Glob()` as well 😄 

Closing this issue - thanks again 👋

**Comment by bmatcuk** [comment]
You're welcome! Glad to help!
