### ISSUE TITLE
Question: double star path matching

### ISSUE THREAD

**Issue by drakkan** [bmatcuk/doublestar#80]
Hello,

Thanks for this useful library!
If you try something like this

```
match, err := doublestar.Match("/mydir/**", "/mydir")
fmt.Printf("match %v, err %v\n", match, err)
```

you will see that there is a match. I looked at the test cases and I know this is by [purpose](https://github.com/bmatcuk/doublestar/blob/master/doublestar_test.go#L101).

I would have expected something like this

https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2Fmydir%2F%2A%2A&matches=false&tests=%2Fmydir&tests=%2Fmydir1&tests=%2Fmydir%2Fa&tests=%2Fmydir%2Fa%2Fb&tests=%2Fmydir%2Fa%2Fb%2Ffile.txt

But I could also be misunderstanding something here. Any clarification would be appreciated, thanks!

**Comment by bmatcuk** [comment]
I based the behavior on bash, which will match `mydir`. For example, if you run the following inside the `test` directory built by doublestar's test suite:

```bash
$ shopt -s globstar
$ for i in a/**; do echo $i; done
a/
a/abc
a/b
a/b/c
a/b/c/d
a/c
a/c/b
```

**Comment by drakkan** [comment]
Thanks, you are right, bash will match `mydir`, but every other glob library I've tested won't. For example this [one](https://globster.xyz/), or python `fnmatch`

```
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fnmatch
>>> fnmatch.fnmatch("/mydir","/mydir/**")
False
>>> fnmatch.fnmatch("/mydir/","/mydir/**")
True
>>> fnmatch.fnmatch("/mydir/a","/mydir/**")
True
```

anyway thanks for the explanation and feel free to close if you think it's the correct behaviour. Not a big deal for my use case

**Comment by bmatcuk** [comment]
Hmm, that's interesting... Personally, I think the doublestar behavior is more consistent: if `mydir` exists on disk, `Glob(fsys, "mydir/**")` will return it, so I would expect `Match` to also return true. But it's a bit of a corner case because both of the examples you provided (digital ocean + fnmatch) _do_ return true as long as you add a trailing slash (such as your second test case with fnmatch above).

In any event, I'm hesitant to change it in doublestar because it has behaved this way for as long as I can remember and I know the second I change it, I'll get a bug report from someone, lol. Do you have a workaround that will fix the issue for your case?

**Comment by drakkan** [comment]
I understand, it's not an issue for my use case, just a matter of documenting the behavior if anyone ever complains, thanks
