### ISSUE TITLE
Allow skipping validation when `Match`ing

### ISSUE THREAD

**Issue by wingsofovnia** [bmatcuk/doublestar#92]
`doMatchWithSeparator` does support turning off validation
https://github.com/bmatcuk/doublestar/blob/180028ba525d3116cc917ac3179e79428acfd89c/match.go#L74

However, it's public counter part doesn't and always enables validation:
https://github.com/bmatcuk/doublestar/blob/180028ba525d3116cc917ac3179e79428acfd89c/match.go#L52-L53

Allowing matching without validation can save some cycles in the use cases where glob patterns have been already validated at an earlier point. A suggested (public) func may look like:
```go
func MatchUnvalidated(pattern, name string) (bool, error) {
	return matchWithSeparator(pattern, name, '/', false)
}
```

**Comment by jbedard** [comment]
I've been having the same performance concerns for a while, also from a bazel gazelle extension where the same globs are invoked a significant number of times.

**Comment by bmatcuk** [comment]
Sorry I haven't replied to this in so long - life is busy 😢 

So, the `validate` flag to `doMatchWithSeparator` only affects one case: when matching reaches the end of `name` before reaching the end of `pattern`, ie, in something like `Match("a/b/c", "a")`.

https://github.com/bmatcuk/doublestar/blob/424062b06d944bcf70c4e2f19b49a032af0dabe0/match.go#L286-L288

That's the only case `Match` runs validation. So, I wouldn't expect a _huge_ performance improvement from a `MatchUnvalidated`. But, I suppose if matching is run many, many times, it would add up.

I cut a v4.7.0 which includes a `MatchUnvalidated`. It only returns a bool instead of `bool, error`.
